// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtCHw57QYCmVzgozV2bWmfXzmBD5Fc9HQ',
    appId: '1:147560897595:web:1794ca8e5f8df29042501e',
    messagingSenderId: '147560897595',
    projectId: 'reminder-b7162',
    authDomain: 'reminder-b7162.firebaseapp.com',
    storageBucket: 'reminder-b7162.firebasestorage.app',
    measurementId: 'G-TKT9NJR3NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl99ytOo7DFCqqCLSqmNXJUb5woux7KPQ',
    appId: '1:147560897595:android:3dad02b3e1d4814542501e',
    messagingSenderId: '147560897595',
    projectId: 'reminder-b7162',
    storageBucket: 'reminder-b7162.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0bYPYHLxpuhhU24Dpc_2YK7BIa9l4-hY',
    appId: '1:147560897595:ios:eb8464ec15775dea42501e',
    messagingSenderId: '147560897595',
    projectId: 'reminder-b7162',
    storageBucket: 'reminder-b7162.firebasestorage.app',
    iosBundleId: 'com.example.reminder',
  );
}
